name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: devMohamed-Hassan
          outputs: |
            ./github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake.svg
          color_snake: "#00FF99"
          color_dots: "#39FF14,#FFD700,#00BFFF,#FF1493,#FF4500"
          color_empty: "#222222"
          color_back: "#000000"
          pixel_size: 12
          speed: 2
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate snake animation"
          add: "output/github-contribution-grid-snake.svg"